[package]
name = "axi-distribution"
version = "0.0.1"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
cache-key = { path = "../cache-key" }
distribution-filename = { path = "../distribution-filename", features = ["serde"] }
distribution-types = { path = "../distribution-types" }
install-wheel-rs = { path = "../install-wheel-rs" }
pep440_rs = { path = "../pep440-rs" }
pep508_rs = { path =     "../pep508-rs" }
platform-tags = { path = "../platform-tags" }
axi-cache = { path = "../axi-cache" }
axi-client = { path = "../axi-client" }
axi-extract = { path = "../axi-extract" }
axi-fs = { path = "../axi-fs", features = ["tokio"] }
axi-git = { path = "../axi-git", features = ["vendored-openssl"] }
axi-normalize = { path = "../axi-normalize" }
axi-traits = { path = "../axi-traits" }
pypi-types = { path = "../pypi-types" }

anyhow = { workspace = true }
fs-err = { workspace = true }
futures = { workspace = true }
nanoid = { workspace = true }
reqwest = { workspace = true }
rmp-serde = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true , features = ["derive"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["compat"] }
tracing = { workspace = true }
url = { workspace = true }
zip = { workspace = true }
