[package]
name = "puffin"
version = "0.0.3"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
default-run = "puffin"

[lints]
workspace = true

[dependencies]

# This tells flate2 (and all libraries that depend on it, including async_compression
# and async_zip) to use zlib-ng, which about 2x faster than the default flate2 backend
# at decompression. See https://github.com/rust-lang/flate2-rs#backends
flate2 = { workspace = true, default-features = false }

[features]
default = ["flate2-zlib-ng"]
# Introduces a dependency on a local Python installation.
python = []
# Introduces a dependency on PyPI.
pypi = []
# Introduces a dependency on Git.
git = []
# Introduces a dependency on Maturin.
maturin = []
# Adds the `libz-ng` feature to flate2.
flate2-zlib-ng = ["flate2/zlib-ng"]
# Adds the `rust_backend` feature to flate2.
flate2-rust_backend = ["flate2/rust_backend"]
